// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkZ1z6PmLvEqzDYYv0Mxnqyawz_T-G6sI',
    appId: '1:926041244920:web:1b2bb3ed8504e903b5a70d',
    messagingSenderId: '926041244920',
    projectId: 'tsunami-4167a',
    authDomain: 'tsunami-4167a.firebaseapp.com',
    databaseURL: 'https://tsunami-4167a-default-rtdb.firebaseio.com',
    storageBucket: 'tsunami-4167a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBakAk_zeiODxNoI3wDxqp0xLCjjPx4t1U',
    appId: '1:926041244920:android:ba970330e1b57dcbb5a70d',
    messagingSenderId: '926041244920',
    projectId: 'tsunami-4167a',
    databaseURL: 'https://tsunami-4167a-default-rtdb.firebaseio.com',
    storageBucket: 'tsunami-4167a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMKNtWGWrpEGwzW_4doG9H3PeLfXkeidI',
    appId: '1:926041244920:ios:30687bc7dc1b8990b5a70d',
    messagingSenderId: '926041244920',
    projectId: 'tsunami-4167a',
    databaseURL: 'https://tsunami-4167a-default-rtdb.firebaseio.com',
    storageBucket: 'tsunami-4167a.firebasestorage.app',
    iosClientId: '926041244920-nd2nis527e266mpge34a7jjdta0qib8s.apps.googleusercontent.com',
    iosBundleId: 'com.tsunami.tsunamiMoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMKNtWGWrpEGwzW_4doG9H3PeLfXkeidI',
    appId: '1:926041244920:ios:30687bc7dc1b8990b5a70d',
    messagingSenderId: '926041244920',
    projectId: 'tsunami-4167a',
    databaseURL: 'https://tsunami-4167a-default-rtdb.firebaseio.com',
    storageBucket: 'tsunami-4167a.firebasestorage.app',
    iosClientId: '926041244920-nd2nis527e266mpge34a7jjdta0qib8s.apps.googleusercontent.com',
    iosBundleId: 'com.tsunami.tsunamiMoney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkZ1z6PmLvEqzDYYv0Mxnqyawz_T-G6sI',
    appId: '1:926041244920:web:1598e7e317fe5cdab5a70d',
    messagingSenderId: '926041244920',
    projectId: 'tsunami-4167a',
    authDomain: 'tsunami-4167a.firebaseapp.com',
    databaseURL: 'https://tsunami-4167a-default-rtdb.firebaseio.com',
    storageBucket: 'tsunami-4167a.firebasestorage.app',
  );
}
